config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'
  resources :consumos
  resources :funcionarios
  resources :veiculos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  match '*path' => redirect('/'), via: :get
end

app/models/veiculo.rb
# == Schema Information
#
# Table name: veiculos
#
#  id         :integer          not null, primary key
#  ano        :integer
#  modelo     :string
#  placa      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Veiculo < ApplicationRecord

    has_many :consumos

    scope :do_funcionario, -> (user_id) { where("id = ?", Funcionario.do_user(user_id).first.veiculo.id)}

    def to_s
      "#{self.placa}/#{self.ano}"
    end

    def consumo_medio
      total = self.total()
      count = self.consumos.count == 0 ? 1 : self.consumos.count 
      "R$ #{total/count}"
    end

    def consumo_total
      "R$ #{ self.total }"
    end

    def total
      self.consumos.map{|c| c.valor}.sum
    end

end

app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  before_action :set_veiculo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /veiculos/
  # GET /veiculos.json
  def index
    @veiculos = Veiculo.all
  end


  # GET /veiculos/1
  # GET /veiculos/1.json
  def show
  end

  # GET /veiculos/new
  def new
    @veiculo = Veiculo.new
  end

  # GET /veiculos/1/edit
  def edit
  end

  # POST /veiculos
  # POST /veiculos.json
  def create
    @veiculo = Veiculo.new(veiculo_params)

    respond_to do |format|
      if @veiculo.save
        format.html { redirect_to @veiculo, notice: 'Veiculo was successfully created.' }
        format.json { render :show, status: :created, location: @veiculo }
      else
        format.html { render :new }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /veiculos/1
  # PATCH/PUT /veiculos/1.json
  def update
    respond_to do |format|
      if @veiculo.update(veiculo_params)
        format.html { redirect_to @veiculo, notice: 'Veiculo was successfully updated.' }
        format.json { render :show, status: :ok, location: @veiculo }
      else
        format.html { render :edit }
        format.json { render json: @veiculo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /veiculos/1
  # DELETE /veiculos/1.json
  def destroy
    @veiculo.destroy
    respond_to do |format|
      format.html { redirect_to veiculos_url, notice: 'Veiculo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veiculo
      @veiculo = Veiculo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veiculo_params
      params.require(:veiculo).permit(:modelo, :placa, :ano)
    end
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/veiculos/_form.html.erb
<%= form_with(model: veiculo, local: true) do |form| %>
  <% if veiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(veiculo.errors.count, "error") %> prohibited this veiculo from being saved:</h2>

      <ul>
      <% veiculo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.text_field :modelo , class:"mdl-textfield__input"%>
    <%= form.label :modelo , class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.text_field :placa, class:"mdl-textfield__input" %>
    <%= form.label :placa, class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.number_field :ano, class:"mdl-textfield__input" %>
    <%= form.label :ano, class:"mdl-textfield__label" %>
  </div>

  <div class="actions">
    <%= form.submit 'Salvar', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
  </div>
<% end %>

app/views/veiculos/edit.html.erb
<h4>Editar Veiculo</h4>

<%= render 'form', veiculo: @veiculo %>
<hr/>
<%= link_to 'Show', @veiculo, class:"mdl-button mdl-js-button mdl-button--accent" %> 
<%= link_to 'Back', veiculos_path, class:"mdl-button mdl-js-button mdl-button--primary" %>

app/views/veiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Veículos</h4>

<table class="mdl-data-table mdl-js-data-table mdl-cell mdl-cell--10-col">
  <thead>
    <tr>
      <th class="">ID</th>
      <th class="">Modelo</th>
      <th class="">Placa</th>
      <th class="mdl-data-table__header--sorted-descending">Ano</th>
      <th colspan=""></th>
    </tr>
  </thead>

  <tbody>
    <% @veiculos.each do |veiculo| %>
      <tr>
        <td><%= link_to veiculo.id, veiculo %></td>
        <td><%= veiculo.modelo %></td>
        <td><%= veiculo.placa %></td>
        <td><%= veiculo.ano %></td>
        <td><%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_veiculo_path(veiculo), class:"mdl-button mdl-js-button mdl-button--accent mdl-button--icon" %>
        <%= link_to '<i class="material-icons">delete_forever</i>'.html_safe, veiculo, method: :delete, data: { confirm: 'Are you sure?' }, class:"mdl-button mdl-js-button mdl-button--icon" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Veiculo', new_veiculo_path, class:"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>

app/views/veiculos/new.html.erb
<h4>Novo Veiculo</h4>

<%= render 'form', veiculo: @veiculo %>
<hr/>
<%= link_to 'Voltar', veiculos_path, class:"mdl-button mdl-js-button mdl-button--primary" %>

app/views/veiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Modelo:</strong>
  <%= @veiculo.modelo %>
</p>

<p>
  <strong>Placa:</strong>
  <%= @veiculo.placa %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @veiculo.ano %>
</p>

<p>
  <strong>Média de Consumo:</strong>
  <%= @veiculo.consumo_medio%>
</p>  

<p>
  <strong>Total Consumido:</strong>
  <%= @veiculo.consumo_total%>
</p>

<hr/>
<%= link_to 'Editar', edit_veiculo_path(@veiculo), class:"mdl-button mdl-js-button mdl-button--accent" %>
<%= link_to 'Voltar', veiculos_path, class:"mdl-button mdl-js-button mdl-button--primary" %>