config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'
  resources :consumos
  resources :funcionarios
  resources :veiculos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  match '*path' => redirect('/'), via: :get
end

app/models/consumo.rb
# == Schema Information
#
# Table name: consumos
#
#  id                 :integer          not null, primary key
#  data_abastecimento :datetime
#  quantidade_litros  :float
#  valor              :float
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  veiculo_id         :integer
#
# Indexes
#
#  index_consumos_on_veiculo_id  (veiculo_id)
#

class Consumo < ApplicationRecord
  belongs_to :veiculo
  
  scope :do_veiculo, -> (veiculo) { where(:veiculo => veiculo)}
  scope :do_funcionario, ->(user_id) { Consumo.do_veiculo(Funcionario.do_user(user_id).first.veiculo.id) }

  scope :is_funcionario, ->(user_id, consumo_id) { Consumo.do_funcionario(user_id).where(:id => consumo_id)}

  scope :do_rank, -> (competencia){
    connection.select_all "select f.nome,
            sum(c.valor) as valor_total,
            sum(c.quantidade_litros) as litros_total
    from
        funcionarios as f
            inner join veiculos as v on f.veiculo_id = v.id
            inner join consumos as c on c.veiculo_id = v.id
    where
        c.data_abastecimento between '#{competencia.strftime("%Y-%m-01")}' and '#{competencia}'
    group by f.nome
    order by valor_total, litros_total desc"
  }

  validates_presence_of :valor, :quantidade_litros, on: [:create, :update], message: "não podem ficar me branco."

  def to_s
    "R$ #{self.valor} - #{self.data_abastecimento.strftime("%d/%m/%Y")}"
  end

end

app/controllers/consumos_controller.rb
class ConsumosController < ApplicationController
  before_action :set_consumo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :possui_permissao?, only: [:edit, :update]
  

  # GET /consumos
  # GET /consumos.json
  def index
    @consumo = Consumo.new
    @consumo.data_abastecimento = Date.today
    @consumos = policy_scope(Consumo).all
  end

  # GET /consumos/1
  # GET /consumos/1.json
  def show
  end

  # GET /consumos/new
  def new
    @consumo = Consumo.new
  end

  # GET /consumos/1/edit
  def edit
  end

  # POST /consumos
  # POST /consumos.json
  def create
    @consumo = Consumo.new(consumo_params)

    respond_to do |format|
      if @consumo.save
        format.html { redirect_to consumos_path, notice: 'Consumo was successfully created.' }
        format.json { render :show, status: :created, location: @consumo }
      else
        format.html { render :new }
        format.json { render json: @consumo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consumos/1
  # PATCH/PUT /consumos/1.json
  def update
    respond_to do |format|
      if @consumo.update(consumo_params)
        format.html { redirect_to consumos_path, notice: 'Consumo was successfully updated.' }
        format.json { render :show, status: :ok, location: @consumo }
      else
        format.html { render :edit }
        format.json { render json: @consumo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consumos/1
  # DELETE /consumos/1.json
  def destroy
    @consumo.destroy
    respond_to do |format|
      format.html { redirect_to consumos_url, notice: 'Consumo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consumo
      @consumo = Consumo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consumo_params
      params.require(:consumo).permit(:data_abastecimento, :valor, :quantidade_litros, :veiculo_id)
    end

    def possui_permissao?
      begin
        redirect_to consumos_url, notice: 'Esse consumo não é seu.' unless !Consumo.is_funcionario(current_user.id, params[:id]).empty?
      rescue => exception
        
      end
    end
end

app/helpers/consumos_helper.rb
module ConsumosHelper

    def veiculos_disponiveis
        if current_user.kind == 1
            return Veiculo.do_funcionario(current_user.id)
        else 
            return Veiculo.all
        end
    end
end

app/views/consumos/_form.html.erb
<%= form_with(model: consumo, local: true) do |form| %>
  <% if consumo.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% consumo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mdl-cell mdl-cell--3-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.date_field :data_abastecimento, class:"mdl-textfield__input" %>
    <%= form.label :data_abastecimento, class:"mdl-textfield__label"  %>
  </div>

  <div class="mdl-cell mdl-cell--2-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.text_field :valor, class:"mdl-textfield__input" %>
    <%= form.label :valor, class:"mdl-textfield__label"  %>
  </div>

  <div class="mdl-cell mdl-cell--2-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.text_field :quantidade_litros, class:"mdl-textfield__input" %>
    <%= form.label "Litros", class:"mdl-textfield__label"  %>
  </div>

  <div class="mdl-cell mdl-cell--2-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.collection_select :veiculo_id, veiculos_disponiveis(), :id, :placa, class:"mdl-textfield__input"%>
    <!-- <%= form.text_field :veiculo_id, class:"mdl-textfield__input"  %> -->
  </div>
  <div class="mdl-cell mdl-cell--2-col mdl-textfield mdl-js-textfield mdl-textfield--floating-label" style="margin: -30px; padding-left: 26px;">
    <%= form.submit "Salvar", class:"mdl-button mdl-js-button mdl-button--raised mdl-button--colored"  %>
  </div>
<% end %>

<script>
  $(document).ready(function(){
    $("#consumo_valor").focus();
  });
</script>

app/views/consumos/edit.html.erb
<h1>Alterar Consumo</h1>

<%= render 'form', consumo: @consumo %>

<hr>
<%= link_to 'Voltar', consumos_path, class:"mdl-button mdl-js-button mdl-button--primary" %>

app/views/consumos/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Consumos</h4>
<%= render 'form', consumo: @consumo %>

<div style="overflow: scroll; height: 350px; overflow-x: hidden;">
  <table class="mdl-data-table mdl-js-data-table mdl-cell mdl-cell--10-col">
    <thead>
      <tr>
        <th>Data abastecimento</th>
        <th>Valor R$</th>
        <th>Litros</th>
        <th>Veiculo</th>
        <th></th>
      </tr>
    </thead>
  
    <tbody>
      <% @consumos.each do |consumo| %>
        <tr>
          <td><%= consumo.data_abastecimento.strftime("%d/%m/%Y") %></td>
          <td><%= consumo.valor %></td>
          <td><%= consumo.quantidade_litros %></td>
          <td><%= link_to consumo.veiculo, veiculo_path(consumo.veiculo) %></td>
          <td><%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_consumo_path(consumo), class:"mdl-button mdl-js-button mdl-button--accent mdl-button--icon" %>
          <%= link_to '<i class="material-icons">delete_forever</i>'.html_safe, consumo, method: :delete, data: { confirm: 'Are you sure?' }, class:"mdl-button mdl-js-button mdl-button--icon" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/consumos/new.html.erb
<h3>Consumos</h1>

<%= render 'form', consumo: @consumo %>

<hr>
<%= link_to 'Voltar', consumos_path, class:"mdl-button mdl-js-button mdl-button--primary" %>

app/views/consumos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data abastecimento:</strong>
  <%= @consumo.data_abastecimento %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @consumo.valor %>
</p>

<p>
  <strong>Quantidade litros:</strong>
  <%= @consumo.quantidade_litros %>
</p>

<p>
  <strong>Veiculo:</strong>
  <%= @consumo.veiculo %>
</p>

<%= link_to 'Edit', edit_consumo_path(@consumo) %> |
<%= link_to 'Back', consumos_path %>