config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'
  resources :consumos
  resources :funcionarios
  resources :veiculos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  match '*path' => redirect('/'), via: :get
end

app/models/funcionario.rb
# == Schema Information
#
# Table name: funcionarios
#
#  id         :integer          not null, primary key
#  nome       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  veiculo_id :integer
#
# Indexes
#
#  index_funcionarios_on_user_id     (user_id)
#  index_funcionarios_on_veiculo_id  (veiculo_id)
#

class Funcionario < ApplicationRecord
  belongs_to :veiculo
  belongs_to :user

  scope :do_user, -> (user) { where(:user => user)}
  scope :do_veiculo, -> (veiculo_id) { where("veiculo_id = ?", veiculo_id)}

end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @user = User.new(user_params)
    @funcionario = Funcionario.new(funcionario_params)
    @funcionario.user = @user

    respond_to do |format|
      if @user.save && @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.user.update(user_params) && @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: 'Funcionario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:veiculo_id, :nome)
    end

    def user_params
      params.require(:funcionario).require(:user).permit(:id, :email, :password, :password_confirmation, :kind)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= nested_form_for(funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% funcionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.text_field :nome, class:"mdl-textfield__input" %>
    <%= form.label :nome, class:"mdl-textfield__label" %>
  </div>

  <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
    <%= form.collection_select :veiculo_id, Veiculo.all, :id, :placa, class:"mdl-textfield__input"%>
    <%= form.label :veiculo_id, class:"mdl-textfield__label" %>
  </div>

  <br/>

  <%= form.fields_for :user do |user_form| %>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= user_form.email_field :email, class:"mdl-textfield__input"%>
      <%= user_form.label :email, class:"mdl-textfield__label" %>
    </div>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= user_form.password_field :password, class:"mdl-textfield__input"%>
      <%= user_form.label :password, class:"mdl-textfield__label" %>
    </div>

    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
      <%= user_form.password_field :password_confirmation, class:"mdl-textfield__input"%>
      <%= user_form.label :password_confirmation, class:"mdl-textfield__label" %>
    </div>

    <%= user_form.hidden_field :kind, :value => User.kinds[:funcionario]%>
  <%end%>


  <div class="actions">
    <%= form.submit 'Salvar', class:"mdl-button mdl-js-button mdl-button--raised mdl-button--colored"%>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h4>Editando Funcionario</h4>

<%= render 'form', funcionario: @funcionario %>

<hr/>
<%= link_to 'Show', @funcionario, class:"mdl-button mdl-js-button mdl-button--accent" %> 
<%= link_to 'Back', funcionarios_path, class:"mdl-button mdl-js-button mdl-button--primary"  %>

app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h4>Funcionários</h4>

<table class="mdl-data-table mdl-js-data-table mdl-cell mdl-cell--10-col">
  <thead>
    <tr>
      <th>ID</th>
      <th>Veiculo</th>
      <th>Nome</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= link_to funcionario.id, funcionario %></td>
        <td><%= funcionario.veiculo %></td>
        <td><%= funcionario.nome %></td>
        <td><%= link_to '<i class="material-icons">edit</i>'.html_safe, edit_funcionario_path(funcionario), class:"mdl-button mdl-js-button mdl-button--accent mdl-button--icon" %>
        <%= link_to '<i class="material-icons">delete_forever</i>'.html_safe, funcionario, method: :delete, data: { confirm: 'Are you sure?' }, class:"mdl-button mdl-js-button mdl-button--icon" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Funcionário', new_funcionario_path, class:"mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--colored" %>

app/views/funcionarios/new.html.erb
<h4>Novo Funcionário</h4>

<%= render 'form', funcionario: @funcionario %>
<hr/>
<%= link_to 'Voltar', funcionarios_path, class:"mdl-button mdl-js-button mdl-button--primary" %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Motorista:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Veiculo:</strong>
  <%= @funcionario.veiculo %>
</p>

<p>
  <strong>Último Consumo:</strong>
  <%= @funcionario.veiculo.consumos.last %>
</p>

<p>
  <strong>Média de Consumo:</strong>
  <%= @funcionario.veiculo.consumo_medio %>
</p>

<hr/>
<%= link_to 'Editar', edit_funcionario_path(@funcionario), class:"mdl-button mdl-js-button mdl-button--accent" %> 
<%= link_to 'Voltar', funcionarios_path, class:"mdl-button mdl-js-button mdl-button--primary" %>