config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'dashboard/index'
  resources :consumos
  resources :funcionarios
  resources :veiculos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboard#index"

  match '*path' => redirect('/'), via: :get
end

app/views/layouts/_card_menu.html.erb
<div class="demo-card-image mdl-card mdl-shadow--2dp">
  <div class="mdl-card__title mdl-card--expand"></div>
  <div class="mdl-card__actions">
    <% if current_user %>
    <span class="demo-card-image__filename">
      <%= current_user.email%></span>
    <% else %>
    <span class="demo-card-image__filename">
      <%= link_to "Entrar", new_user_session_path,  class:"mdl-layout-title" %> </span>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="mdl-layout__header">
  <div class="mdl-layout__header-row">
    <!-- Title -->
    <span class="mdl-layout-title">CathEx</span>
    <!-- Add spacer, to align navigation to the right -->
    <div class="mdl-layout-spacer"></div>
    <!-- Navigation. We hide it in small screens. -->
    <nav class="mdl-navigation mdl-layout--large-screen-only">
      <% if current_user %>
      <a class="mdl-navigation__link" href="">Olá,
        <%= current_user.email%></a>
        <%= link_to  "Sair", destroy_user_session_path, method: :delete, class:"mdl-navigation__link" %>
      <%else%>
        <%= link_to "Entrar", new_user_session_path,  class:"mdl-navigation__link" %>
      <% end %>
    </nav>
  </div>
</header>

app/views/layouts/_main.html.erb
<main class="mdl-layout__content">
  <div class="page-content">
    <div class="mdl-grid">
      <div class="mdl-cell mdl-cell--2-col mdl-cell--6-col-tablet"></div>
      <div class="mdl-cell mdl-cell--10-col mdl-cell--8-col-tablet">
        <p class="alert">
          <%= alert %>
        </p>
        <%= yield %>
      </div>
      <div class="mdl-cell mdl-cell--0-col mdl-cell--4-col-phone"></div>
    </div>
  </div>
</main>

app/views/layouts/_side_bar.html.erb
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <%= render 'layouts/header' %>
  <div class="mdl-layout__drawer">
    <%= render 'layouts/card_menu' %>
    <%= render 'layouts/sub_menus' %>
  </div>
  <%= render 'layouts/main' %>
</div>

app/views/layouts/_sub_menus.html.erb
<!-- <span class="mdl-layout-title">Opções</span> -->
<nav class="mdl-navigation">
  <%=link_to "Rank", dashboard_index_path, class:"mdl-navigation__link"%>
  <% if policy(User).logado? %>  
    <% if policy(User).veiculo? %>
      <%=link_to "Veículos", veiculos_path, class:"mdl-navigation__link"%>
    <% end %>
    <% if policy(User).funcionario? %>
      <%=link_to "Funcionários", funcionarios_path, class:"mdl-navigation__link"%>
    <% end %>
    <%=link_to "Consumos", consumos_path, class:"mdl-navigation__link"%>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CathEx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.blue_grey-indigo.min.css" />
    <!-- <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.red-indigo.min.css" /> -->
  </head>

  <body>
      <%= render 'layouts/side_bar' %>
  </body>
</html>